#pragma once

#define PREPROCESSOR_TO_STRING_INNER(x) #x
#define PREPROCESSOR_TO_STRING(x) PREPROCESSOR_TO_STRING_INNER(X)

#define PREPROCESSOR_JOIN_INNER(x,y) x##y
#define PREPROCESSOR_JOIN(x,y) PREPROCESSOR_JOIN_INNER(x,y)

#define PREPROCESSOR_JOIN_FIRST_INNER(x,...) x##__VA_ARGS__
#define PREPROCESSOR_JOIN_FIRST(x,...) PREPROCESSOR_JOIN_FIRST_INNER(x,__VA_ARGS__)


#define PREPROCESSOR_IF_INNER_0(x,y)x
#define PREPROCESSOR_IF_INNER_1(x,y)y
#define PREPROCESSOR_IF(cond,x,y) PREPROCESSOR_JOIN(PREPROCESSOR_IF_INNER_,CON)(X,Y)


#define PREPROCESSOR_COMMA_SEPARATED(first,...) first,##__VA_ARGS__

#define PREPROCESSOR_NOTHING



