#pragma once
#include "Platform.h"
#include "RHIDefinitions.h"

enum EShaderPlatform :uint16
{
	SP_PCD3D_SM5 = 0,
	SP_METAL = 11,
	SP_METAL_MRT = 12,
	SP_PCD3D_ES3_1 = 14,
	SP_OPENGL_PCES3_1 = 15,
	SP_METAL_SM5 = 16,
	SP_VULKAN_PCES3_1 = 17,
	SP_METAL_SM5_NOTESS_REMOVED	=18,
	SP_VULKAN_SM5 = 20,
	SP_VULKAN_ES3_1_ANDROID = 21,
	SP_METAL_MACES3_1 = 22,
	SP_OPENGL_ES3_1_ANDROID = 24,
	SP_METAL_MRT_MAC = 27,
	SP_VULKAN_SM5_LUMIN_REMOVED	 = 28,
	SP_VULKAN_ES3_1_LUMIN_REMOVED = 29,
	SP_METAL_TVOS = 30,
	SP_METAL_MRT_TVOS = 31,
	SP_StaticPlatform_First = 32,

#ifdef DDPI_EXTRA_SHADERPLATFORMS
	DDPI_EXTRA_SHADERPLATFORMS
#endif
	SP_PCD3D_SM6,
	SP_D3D_ES3_1_HOLOLENS,
	SP_CUSTOM_PLATFORM_FIRST,
	SP_CUSTOM_PLATFORM_LAST = (SP_CUSTOM_PLATFORM_FIRST + 100),
	SP_NumPlatforms,
	SP_NumBits = 16,
};